### ISSUE TITLE
Persisting timeline list items without annotations in VIA save

### ISSUE THREAD

**Issue by willprice** [ox-vgg/via#10]
Hi, 

Thanks for the great tool. One improvement would be to save the streams in the "Timeline List" regardless of whether they have any annotations in them or not. Currently, the tool discards any streams that don't have any annotations when reloading the saved project.

**Comment by thelinuxmaniac** [comment]
Thank you. We will add the requested behaviour in the next release of VIA3.

PS: Please use https://gitlab.com/vgg/via/-/issues for future posts as the github repository is just a mirror of our gitlab repository where all the development and discussion takes place.

**Comment by thelinuxmaniac** [comment]
Follow up: https://gitlab.com/vgg/via/-/issues/269

**Comment by thelinuxmaniac** [comment]
done in https://gitlab.com/vgg/via/-/tags/via-3.0.7
